version: '3'
services:
  backend:
    build:
      context: ./joker_backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./joker_backend:/app/backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./joker_frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./joker_frontend:/app/frontend
    depends_on:
      - backend
  
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/

volumes:
  joker_backend: